version: "3.8"

services:
  phoenix:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Elixir Version: 1.9, 1.10, 1.10.4, ...
        ELIXIR_VERSION: "1.13.1"
        # Phoenix Version: 1.4.17, 1.5.4, ...
        PHOENIX_VERSION: "1.6.2"
        # Node Version: 10, 11, ...
        NODE_VERSION: "16.7.0"
    environment:
      # Variables to connect to our Postgres server
      PGUSER: postgres
      PGPASSWORD: postgres
      # PGDATABASE: database_name
      PGPORT: 5432
      # Hostname of our Postgres container
      PGHOST: db
    # Mapping the port to make the Phoenix app accessible outside of the container
    ports:
      - 4000:4000
    # The db container needs to be started before we start this container
    depends_on:
      - db
    # you need to enable sharing in the windows docker app
    # volumes:
    #   - ./src:/app
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  db:
    # We use the predefined Postgres image
    image: postgres:latest
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # POSTGRES_DB: database_name
      # Set a path where Postgres should store the data
      # PGDATA: /var/lib/postgresql/data/pgdata
    restart: unless-stopped
    # ports:
    #   - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
# Define the volumes
volumes:
  pgdata: null
